from enum import Enum


class Expansion(Enum):
    NONE = ''
    ORGANIZER = 'organizer'
    GAME = 'game'


class MatchType(Enum):
    ALL = 'all'
    UPCOMING = 'upcoming'
    ONGOING = 'ongoing'
    PAST = 'past'


class Game(Enum):
    RL_XBOX_PC = 'rl_XBOX_PC'
    WOT_XBOX = 'wot_xbox'
    WOT_NA = 'wot_NA'
    WOT_RU = 'wot_RU'
    WOT_EU = 'wot_EU'
    SMITE_XBOX = 'smite_xbox'
    SMITE = 'smite'
    DIRTY_BOMB = 'dirtybomb'
    NHL_20_XBOX = 'nhl_20_xbox'
    NHL_19_XBOX = 'nhl_19_XBOX'
    NHL_18_XBOX = 'nhl_18_XBOX'
    NHL_20_PS4 = 'nhl_20_ps4'
    NHL_19_PS4 = 'nhl_19_PS4'
    NHL_18_PS4 = 'nhl_18_PS4'
    NHL_19 = 'nhl_19'
    NHL_20 = 'nhl_20_parent'
    APEX = 'apex'
    MINION_MASTERS = 'minion_masters'
    HALO_3 = 'halo_3'
    HALO_5_XBOX = 'halo_5'
    HALO_INFINITE = 'halo_infinite'
    HALO_MCC = 'halo_mcc'
    RAINBOW6S_PS4 = 'gs_rainbow_6_ps4'
    RAINBOW6S_XBOX = 'gs_rainbow_6_xbox'
    RAINBOW6S_PC = 'gs_rainbow_6'
    RAINBOW6S = 'rainbow_6'
    WARFACE_EU = 'warface_eu'
    WARFACE_NA = 'warface_na'
    WARFACE_ALPHA = 'warface_alpha'
    WARFACE_PARENT = 'warface_parent'
    WARFACE = 'warface'
    BRAWL_STARS_AUTO = 'brawl_stars_auto'
    BRAWL_STARS = 'brawl_stars'
    OVERWATCH_EU = 'overwatch_EU'
    OVERWATCH_US = 'overwatch_US'
    OVERWATCH_KR = 'overwatch_KR'
    OVERWATCH = 'overwatch'
    CLASH_ROYALE_AUTO = 'clash_royale_auto'
    CLASH_ROYALE = 'clash_royale'
    DESTINY_2_XBOX = 'destiny2_xbox'
    DESTINY_2_PS4 = 'destiny2_ps4'
    DESTINY_2_PC = 'destiny2'
    DESTINY_2 = 'destiny2_parent'
    LOL_TR = 'lol_TR'
    LOL_EUN = 'lol_EUN'
    LOL_EUW = 'lol_EUW'
    LOL_OCE = 'lol_OCE'
    LOL_BR = 'lol_BR'
    LOL_LAN = 'lol_LAN'
    LOL_LAS = 'lol_LAS'
    LOL_NA = 'lol_NA'
    LOL = 'Wild'
    LOL_PARENT = 'lol_parent'
    KRUNKER = 'krunker'
    RING_OF_ELYSIUM = 'ring_of_elysium'
    TF2 = 'tf2'
    CS_DZ = 'csdz'
    VALORANT = 'valorant'
    Dota_2 = 'dota2'
    TEMPERIA = 'temperia'
    HS_BATTLEGROUNDS = 'hearthstone-battlegrounds'
    FIFA22 = 'fifa22'
    FIFA20 = 'fifa20'
    WOW = 'wow'
    QUAKE_CHAMPIONS = 'quake_champions'
    TRACKMANIA = 'trackmania'
    PUBG = 'pubg'
    NEW_STATE_MOBILE = 'newstate'
    RIFT = 'wildrift'
    HEARTHSTONE = 'hearthstone'
    FALLGUYS = 'fallguys'
    TEAMFIGHT_TACTICS = 'teamfight_tactics'
    PUBG_MOBILE = 'pubgmobile'
    ROCKET_LEAGUE = 'rocket_league'
    CS_GO = 'csgo'
